# Generated by Django 4.2 on 2023-08-01 03:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_discount', models.CharField(blank=True, choices=[('процент', 'процент'), ('количество', 'количество'), ('процент и количество', 'процент и количество')], max_length=20, null=True, verbose_name='тип скидки')),
                ('start_discount', models.DateTimeField()),
                ('end_discount', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания скидки')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность скидки')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='процентная скидка')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='количественная скидка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='app_catalog.productinshop', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
